apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-generation-service
  namespace: content-automation
  labels:
    app: content-generation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-generation-service
  template:
    metadata:
      labels:
        app: content-generation-service
    spec:
      containers:
      - name: content-generation-service
        image: gcr.io/${PROJECT_ID}/content-generation-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: content-generation-config
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: model-cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: content-generation-service
  namespace: content-automation
spec:
  selector:
    app: content-generation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP 