apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-discovery-service
  namespace: content-automation
  labels:
    app: topic-discovery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: topic-discovery-service
  template:
    metadata:
      labels:
        app: topic-discovery-service
    spec:
      containers:
      - name: topic-discovery-service
        image: gcr.io/${PROJECT_ID}/topic-discovery-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: topic-discovery-config
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: topic-discovery-service
  namespace: content-automation
spec:
  selector:
    app: topic-discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP 