apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-prioritization-service
  namespace: content-automation
  labels:
    app: topic-prioritization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: topic-prioritization-service
  template:
    metadata:
      labels:
        app: topic-prioritization-service
    spec:
      containers:
      - name: topic-prioritization-service
        image: gcr.io/${PROJECT_ID}/topic-prioritization-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: topic-prioritization-config
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/torch
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: model-cache
        emptyDir: {}
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key

---
apiVersion: v1
kind: Service
metadata:
  name: topic-prioritization-service
  namespace: content-automation
spec:
  selector:
    app: topic-prioritization-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP 